---
title: "NCOS pre and post restoration bird survey analysis"
author: "Carmen Galaz-García"
date: "6/6/2021"
output: 
  html_document:
    #toc: true  # make a table of contents
    #toc_float: true  # table of contents as sidebar
    #number_sections: true  
    code_folding: hide  # makes hide/show for code---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(tsibble)
```

# About the data
The pre-restoration data corresponds to CCBER surveys taking place in the South Parcel and Ocean Meadows Golf Course from July 2011 to August 2013.
The post-restoration data corresponds to CCBER surveys taking place at North Campus Open Space from July 2011 to August 2013.
## Data Selection

```{r}
# ----- Bird common names from bbl_codes ----

bbl_codes <- read_csv(here("BBL_codes.csv")) %>% 
  clean_names() %>% 
  select(!common_name_aka)

bird_types <- read_csv(here("bird_types.csv")) %>% 
  select(!e_bird_group)
```


```{r}
# ---- PRE-RESTORATION DATA SELECTION ----

# --- raw pre-restoration data
raw_pre_surveys <- read.csv(here('CCBER_data_and_script_files','survey_data.csv')) %>%
  clean_names() %>% 
  mutate

# ------------------------------
# selecting all CCBER observations for 
#     Ocean Meadows Golf Course AND South Parcel
# all CCBER observations have 
#    confidence = 2, 
#    present_absent = P or yes
#    num_locations = 1 
#    location2, location3, location 4 = NA

pre_ccber_surveys <- raw_pre_surveys %>% 
  filter(source1 == "CCBER") %>% 
  mutate(date = mdy(date)) %>% 
  select(date,
         location1, 
         total_count,
         bbl_code) %>% 
  filter(location1 %in% c("OMG","SP")) %>%
  left_join(y=bbl_codes,by="bbl_code") %>%    # --- add common names
  left_join(y=bird_types, by = c("common_name" = "species")) %>%  # --- add general_type
  select(date, total_count, common_name, general_type) %>% 
  rename(count = total_count) %>% 
  relocate(common_name, .after = date)
  

rm(bbl_codes)
rm(bird_types)
rm(raw_pre_surveys)


# ---- check which remain with NA name or NA type
# no_name <-  ccber_surveys %>% 
#   filter(is.na(common_name))
# 
# no_type <- ccber_surveys %>% 
#   filter(is.na(general_type))

```


```{r}
# ---- POST-RESTORATION DATA SELECTION ----

# --- raw post-restoration data
raw_post_surveys <- read.csv(here('data','COPR_NCOS_Bird_Survey_Data_Aug2017_Aug2019.csv')) %>% 
  clean_names()

# ------------------------------
# selecting all CCBER bird surveys for NCOS from 2016 onward
post_ccber_surveys <- raw_post_surveys %>% 
  # --- date formatting and selection ---
  mutate(observation_date = lubridate::mdy(observation_date)) %>%
  filter( 2016 <= year(observation_date),
          location == "NCOS") %>% 
  # --- column simplification ---
  select(observation_date, 
         species,
         general_type,
         count) %>% 
  rename(date = observation_date,
         common_name = species) %>% 
  relocate(count, .after=common_name)

rm(raw_post_surveys)
```

```{r, include=FALSE}


#  -------- TYPE ABUNDANCE ----------------
# Count number of individuals per type and observation (all NCOS data)
# type_count <- all_surveys %>% 
#   select(date, count, general_type) %>% 
#   count(date, general_type, 
#         wt=count) 
# 
# ggplot(data= type_count, aes(x=date, y=n)) +
#   geom_line()+
#   facet_wrap(~general_type) +
#   theme_light()+
#   theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
#   labs(title="Monthly bird counts at OMGC and South Parcel abundance by general type",
#        x="observation date",
#        y= "number of individuals registered (n)")
```


```{r, include = FALSE}
# month_type_count <- type_count
#   as_tsibble(key = general_type, index=date) %>% 
#   index_by( month =  ~yearmonth(.)) %>%   # group by month
#   group_by(general_type) %>% 
#   #summarise(monthly_count = sum(n))
#   summarise(monthly_mean = mean(n))

# 
# ggplot(data= month_type_count, aes(x=month, y=monthly_mean)) +
#   geom_line()+
#   facet_wrap(~general_type) +
#   theme_light()+
#   theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
#   labs(title="Average monthly bird counts at \nOMGC and South Parcel, grouping by general type",
#        x="observation date",
#        y= "average number of individuals registered ")
```


# Abundance by guild


```{r}
# Bind pre and post restoration surveys
all_surveys <- bind_rows(pre_ccber_surveys,post_ccber_surveys) %>% 
  filter(!is.na(general_type))
general_types <- unique(all_surveys$general_type)

type_graph <- function(dataf, gen_type){
  type_count <- dataf %>% 
    filter(general_type == gen_type) %>% 
    select(date, count, general_type) %>% 
    count(date, general_type, 
        wt=count) 
  
  plot <- ggplot(data= type_count, aes(x=date, y=n)) +
    geom_line()+
    theme_light()+
    theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
    labs(title= paste("Abundance of", gen_type, "guild at NCOS", sep=" "),
         x="observation date",
         y= "number of individuals registered (n)")  
  
  return(plot)  
}


for (i in general_types){
  print(type_graph(all_surveys, i))
}

```


