---
title: "NCOS Bird Diversity Exploration"
author: "Carmen Galaz-García"
date: "5/5/2021"
output: 
  html_document:
    toc: true  # make a table of contents
    toc_float: true  # table of contents as sidebar
    #number_sections: true  
    code_folding: hide  # makes hide/show for code---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(tsibble)
library(stringr)

# raw data
post_survey_data <- read.csv(here('data','COPR_NCOS_Bird_Survey_Data_Aug2017_Aug2019.csv')) %>% 
  clean_names()

```


```{r}
# ------------------- DATA SELECTION ------------------------

post_restoration <- post_survey_data %>% 
  # --- date formatting and selection ---
  mutate(observation_date = lubridate::mdy(observation_date)) %>%
  filter( 2016 <= year(observation_date)) %>% 
  # --- location formatting and selection ---
  mutate(location = replace(location, location =="Devereux Slough", "DEVEREUX SLOUGH")) %>% 
  filter(!(location %in% c("BEACH SOUTH", "BEACH NORTH", "OUT OF POLYGON"))) %>% 
  mutate(region = case_when( location == "NCOS" ~ "NCOS",
                              location != "NCOS" ~ "DEV" )) %>% 
  # --- column simplification ---
  select(observation_date, 
         species,
         general_type,
         count,
         region) 
```

```{r, include=FALSE}
# OWLS
owls <- post_survey_data %>% 
  filter(str_detect(species, "great") )
unique(owls$species)
```

## Abundance per type


```{r}

# -------- TYPE ABUNDANCE ----------------
# Count number of individuals per type, observation date and location
type_count <- post_restoration %>% 
  select(!species) %>% 
  count(observation_date, region, general_type, 
        wt=count)

# ------- GRAPH ------

ggplot(data= type_count, aes(x=observation_date, y=n)) +
  geom_line(aes(col=region))+
  facet_wrap(~general_type) +
  theme_light()+
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(title="Comparison of monthly bird counts at Deveroux Slough and NCOS \ngrouping by general type",
       x="observation date",
       y= "number of individuals registered (n)")

```

<br>
<br>
<br>
<br>

## Species abundance
<br>
<br>



```{r}
# ------- SPECIES ABUNDANCE ----------

# Count number of individuals per species, observation date and region (Dev/NCOS)
# Keeps associated general type and location
species_count <- post_restoration %>% 
  unite("species_and_type", species, general_type, sep="*") %>% 
  count(observation_date, region, species_and_type,
        wt=count) %>% 
  separate(species_and_type, c("species","general_type"), sep="([*])") 
```


```{r}
# ------ TYPE AND LOCATION SELECTION ----
select_type_location <- function(data,type,region1){
  subset <- data %>% 
    filter(general_type == type,
           region == region1)
  return(subset)
}

# ----- HIGH COUNT THRESHHOLD -----
count_thresh <- function(data,max){
  new_data <- data %>% 
    mutate(species = case_when( n < max ~ "other",
                              n >= max ~ species)) 
  return(new_data)
}

```


### Insectivores

```{r}

insectivores_species_NCOS <- species_count %>% 
  select_type_location(type="Insectivores", region1="NCOS") %>% 
  count_thresh(max=25)

insectivores_count_DEV <- type_count %>% 
  select_type_location(type="Insectivores", region1="DEV") 

# --------------------------------------------------------------------
ggplot() + 
  # --- NCOS count by species ---
    geom_bar(data = insectivores_species_NCOS,
             position="stack", 
             stat="identity", 
             aes(fill=species, y=n, x=observation_date))+
    scale_fill_manual(values = c("#FFDB6D", "#C4961A", "#D16103","azure3", 
                "#C3D7A4", "#52854C", "#4E84C4", "darkorchid"))+
  # --- DEV total count ---
    geom_line(data=insectivores_count_DEV, 
              aes(x=observation_date, y=n, col=region))+
    scale_colour_grey()+
  # --- themes ---
    labs(title="Insectivores at NCOS (09/2017-08/2019)",
         y = "number of individuals registered (n)") +
    theme_light()+
    theme( # remove the vertical grid lines
           panel.grid.major.x = element_blank() ,
           panel.grid.minor.x = element_blank() ,
    )

```


**Graph 2.** Other species had a count of less than 25 individuals on a given date.

### Seed & Fruit Eaters

```{r}

seed_species_NCOS <- species_count %>% 
  select_type_location(type="Seed & Fruit Eaters", region1="NCOS") %>% 
  count_thresh(max=20)

seed_count_DEV <- type_count %>% 
  select_type_location(type="Seed & Fruit Eaters", region1="DEV") 

# --------------------------------------------------------------------

ggplot() + 
    geom_bar( data = seed_species_NCOS,
             position="stack", 
             stat="identity", 
             aes(fill=species, y=n, x=observation_date))+
    scale_fill_manual(values = c("#4E84C4", "#C4961A", "azure3", "#D16103","#C3D7A4"))+
    geom_line(data=seed_count_DEV, 
              aes(x=observation_date, y=n, col=region))+
    scale_colour_grey()+
  labs(title="Seed and Fruit Eaters at NCOS (09/2017-08/2019)",
       y = "number of individuals registered (n)")+
  theme_light()+
  theme( # remove the vertical grid lines
           panel.grid.major.x = element_blank() ,
           panel.grid.minor.x = element_blank() ,
    )

```

**Graph 3.** Other species had a count of less than 20 individuals on a given date.

<br>
<br>

### Omnivores

```{r}

omnivores_species_NCOS <- species_count %>% 
  select_type_location(type="Omnivores", region1="NCOS") %>% 
  count_thresh(max=10)

omnivores_count_DEV <- type_count %>% 
  select_type_location(type="Omnivores", region1="DEV") 

# --------------------------------------------------------------------

ggplot(omnivores_species_NCOS) + 
    geom_bar(position="stack", 
             stat="identity", 
             aes(fill=species, y=n, x=observation_date))+
    scale_fill_manual(values = c("#4E84C4", "#C4961A", "#D16103","azure3"))+
    geom_line(data=omnivores_count_DEV, 
              aes(x=observation_date, y=n, col=region))+
    scale_colour_grey()+
    labs(title="Omnivores at NCOS (09/2017-08/2019)",
         y = "number of individuals registered (n)")+
    theme_light()+
    theme( # remove the vertical grid lines
           panel.grid.major.x = element_blank() ,
           panel.grid.minor.x = element_blank() ,
    )

```

**Graph 4.** Other species had a count of less than 10 individuals on a given date.


## Species Richness


### Total

```{r, include=TRUE}
# ----- Species Richness Analysis in Dev and NCOS -----
richness <- species_count %>% 
  count(region, observation_date) %>% 
  as_tsibble(key=region ,index=observation_date)


ggplot(data=richness, 
       aes(x=observation_date, y=n)) +
  geom_line(aes(col=region))+
  theme_light()+
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(title="Species richness at Deveroux Slough and NCOS (2017-2019)",
       x="observation date",
       y= "number of species registered (n)")+
  theme(legend.position="bottom")

```


### By type

```{r}
# ----- Species Richness Analysis, by type in Dev and NCOS -----

richness_by_type <- species_count %>% 
  count(region, observation_date, general_type) 

ggplot(data= richness_by_type, aes(x=observation_date, y=n)) +
  geom_line(aes(col=region))+
  facet_wrap(~general_type) +
  theme_light()+
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(title="Species richness at Deveroux Slough and NCOS (2017-2019)",
       x="observation date",
       y= "number of species registered (n)")+
  theme(legend.position="bottom")
```